### ISSUE TITLE
Support php 8.1

### ISSUE THREAD

**Issue by JorisDebonnet** [JayBizzle/Laravel-Migrations-Organiser#39]
I noticed `composer.json` requires `php <8.1`. Is there an incompatibility with php 8.1 then? If not, can't we just use `>=8.0`?

**Comment by JayBizzle** [comment]
Everything works with 8.1 so I will get the composer.json update 👍🏻

**Comment by JayBizzle** [comment]
Sorry, just looked into this, and thought i was replying on a different repo.

/ping @dmitryuk 

Can you remember why you set the version constraint to `>=7.3 <=8.0` in https://github.com/JayBizzle/Laravel-Migrations-Organiser/commit/b02638f060a0b7ce0308945342ad73a21e4a047e

**Comment by dmitryuk** [comment]
@JayBizzle 
Yes I remember.
Finally I set `>=7.3 <8.1`, because ’composer install’ command failed with error
`Root composer.json requires php >=7.3 <=8.0 but your php version (8.0.2) does not satisfy that requirement.’

Version 8.1 has not be released at the moment, so nobody knows about supporting of it.
I think if somebody add Travis support of PHP 8.1 and change composer.json same way it will be enough.
